export const jsonData = {
  "049": {
    url: "049",
    name: "SSC Sports Extra 1",
    logo: "https://iili.io/HpLHKZv.png",
    group: "Sports",
  },
  "050": {
    url: "050",
    name: "SSC Sports Extra 2",
    logo: "https://iili.io/HpLHqnR.png",
    group: "Sports",
  },
  "051": {
    url: "051",
    name: "SSC Sports Extra 3",
    logo: "https://iili.io/HpLHBGp.png",
    group: "Sports",
  },
  "052": {
    url: "052",
    name: "DAZN 1",
    logo: "https://iili.io/HpLlhvI.png",
    group: "Sports",
  },
  "053": {
    url: "053",
    name: "DAZN 2",
    logo: "https://iili.io/HpLlXYN.png",
    group: "Sports",
  },
  "054": {
    url: "054",
    name: "ZONA DAZN",
    logo: "https://iili.io/HpLlW2p.png",
    group: "Sports",
  },
  "064": {
    url: "064",
    name: "DAZN La Liga",
    logo: "https://iili.io/HpQyYzJ.png",
    group: "Sports",
  },

  "055": {
    url: "055",
    name: "BEIN SPORTS 1",
    logo: "https://iili.io/HpLlECJ.png",
    group: "Sports",
  },
  "056": {
    url: "056",
    name: "BEIN SPORTS 2",
    logo: "https://iili.io/HpLl0Qa.png",
    group: "Sports",
  },
  "063": {
    url: "063",
    name: "BEIN SPORTS 3",
    logo: "https://iili.io/HpLlGEv.png",
    group: "Sports",
  },

  "057": {
    url: "057",
    name: "Inter Milan TV",
    logo: "https://iili.io/HpLmnAG.png",
    group: "Sports",
  },
  "058": {
    url: "058",
    name: "AC Milan TV",
    logo: "https://iili.io/HpLmC9s.png",
    group: "Sports",
  },
  "062": {
    url: "062",
    name: "Play Sports 1",
    logo: "https://iili.io/HpQ6AR2.png",
    group: "Sports",
  },
  "059": {
    url: "059",
    name: "EURO SPORTS 1",
    logo: "https://iili.io/HpZ3vrx.png",
    group: "Sports",
  },
  "060": {
    url: "060",
    name: "EURO SPORTS 2",
    logo: "https://iili.io/HpZ3SdQ.png",
    group: "Sports",
  },
  "061": {
    url: "061",
    name: "CRICLIFE 3",
    logo: "https://iili.io/HpLmqSn.png",
    group: "Sports",
  },
  "": {
    url: "",
    name: "",
    logo: "",
    group: "",
  },

  jiocinema: {
    url: "https://live.dtvhindi.news/jiocinema",
    name: "JioCinema Web",
    logo: "https://iili.io/d5yeaGS.md.png",
    group: "Website",
  },
  sonyten1: {
    url: "https://vlive.pages.dev/prime?id=sonyten1",
    name: "Sony Sports Ten 1",
    logo: "https://mediaready.videoready.tv/tatasky-epg/image/fetch/f_auto,fl_lossy,q_auto,dpr_6.75,w_40/https://ltsk-cdn.s3.eu-west-1.amazonaws.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-513-j5jzouqw-v5/imageContent-513-j5jzouqw-m7.png",
    group: "Sports",
  },
  sonyten2: {
    url: "https://vlive.pages.dev/prime?id=sonyten2",
    name: "Sony Sports Ten 2",
    logo: "https://mediaready.videoready.tv/tatasky-epg/image/fetch/f_auto,fl_lossy,q_auto,dpr_6.75,w_40/https://ltsk-cdn.s3.eu-west-1.amazonaws.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-742-j5l50le0-v5/imageContent-742-j5l50le0-m7.png",
    group: "Sports",
  },
  sonyten3: {
    url: "https://vlive.pages.dev/prime?id=sonyten3",
    name: "Sony Sports Ten 3",
    logo: "https://mediaready.videoready.tv/tatasky-epg/image/fetch/f_auto,fl_lossy,q_auto,dpr_6.75,w_40/https://ltsk-cdn.s3.eu-west-1.amazonaws.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-739-j5l4y6yw-v5/imageContent-739-j5l4y6yw-m5.png",
    group: "Sports",
  },
  sonyten4: {
    url: "https://vlive.pages.dev/prime?id=sonyten4",
    name: "Sony Sports Ten 4",
    logo: "https://iili.io/21zKjlj.md.png",
    group: "Sports",
  },
  sonyten5: {
    url: "https://vlive.pages.dev/prime?id=sonyten5",
    name: "Sony Sports Ten 5",
    logo: "https://mediaready.videoready.tv/tatasky-epg/image/fetch/f_auto,fl_lossy,q_auto,dpr_6.75,w_40/https://ltsk-cdn.s3.eu-west-1.amazonaws.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-108-j5fl5wwg-v3/imageContent-108-j5fl5wwg-m3.png",
    group: "Sports",
  },
  cl2: {
    url: "https://vlive.pages.dev/prime?id=cl2",
    name: "CRICLIFE 2",
    logo: "https://i.ibb.co/jDyn9fS/Picsart-24-07-27-01-42-37-317.png",
    group: "Sports",
  },

  willow: {
    url: "https://vlive.pages.dev/prime?id=willow",
    name: "Willow SD",
    logo: "https://i.ibb.co/Js5t9dM/Picsart-24-07-27-01-20-13-863.png",
    group: "Sports",
  },
  astro: {
    url: "https://vlive.pages.dev/prime?id=astro2",
    name: "Astro Cricket",
    logo: "https://iili.io/HpsO1kb.png",
    group: "Sports",
  },
  asports: {
    url: "https://live.dtvhindi.news/tv?id=asports",
    name: "A Sports Cricket",
    logo: "https://i.ibb.co/Cmz5VJ6/20240727-020613.png",
    group: "Sports",
  },
  tc: {
    url: "https://vlive.pages.dev/prime?id=tc",
    name: "Ten Cricket",
    logo: "https://iili.io/dXNk3f1.md.png",
    group: "Sports",
  },
  ptvs: {
    url: "https://vlive.pages.dev/prime?id=ptvs",
    name: "PTV SPORTS",
    logo: "https://i.ibb.co/2q6qJmy/20240727-042215.png",
    group: "Sports",
  },
  beinsports1: {
    url: "https://vlive.pages.dev/prime?id=beinsports1",
    name: "Bein Sports 1",
    logo: "https://iili.io/dXNG2zg.md.png",
    group: "Football",
  },
  star1in: {
    url: "https://vlive.pages.dev/crichd?id=star1in",
    name: "Star Sports 1",
    logo: "https://raw.githubusercontent.com/abusaeeidx/Tv-Channel-Logo/heads/main/CricHD/runded/16-by-xfireflix.png",
    group: "Sports",
  },
  starhindi: {
    url: "https://vlive.pages.dev/crichd?id=starhindi",
    name: "Star Sports 1 Hindi",
    logo: "https://raw.githubusercontent.com/abusaeeidx/Tv-Channel-Logo/heads/main/CricHD/runded/1-by-xfireflix.png",
    group: "Sports",
  },
  ptvpk: {
    url: "https://vlive.pages.dev/crichd?id=ptvpk",
    name: "PTV Sports",
    logo: "https://raw.githubusercontent.com/abusaeeidx/Tv-Channel-Logo/heads/main/CricHD/runded/20-by-xfireflix.png",
    group: "Sports",
  },
  willowusa: {
    url: "https://vlive.pages.dev/crichd?id=willowusa",
    name: "Willow HD",
    logo: "https://raw.githubusercontent.com/abusaeeidx/Tv-Channel-Logo/heads/main/CricHD/runded/38-by-xfireflix.png",
    group: "Sports",
  },
  willowextra: {
    url: "https://vlive.pages.dev/crichd?id=willowextra",
    name: "Willow HD 2",
    logo: "https://raw.githubusercontent.com/abusaeeidx/Tv-Channel-Logo/heads/main/CricHD/runded/8-by-xfireflix.png",
    group: "Sports",
  },
  tenspk: {
    url: "https://vlive.pages.dev/crichd?id=tenspk",
    name: "Ten Sports",
    logo: "https://raw.githubusercontent.com/abusaeeidx/Tv-Channel-Logo/heads/main/CricHD/runded/10-by-xfireflix.png",
    group: "Sports",
  },
  asportshd: {
    url: "https://vlive.pages.dev/crichd?id=asportshd",
    name: "A Sports HD",
    logo: "https://raw.githubusercontent.com/abusaeeidx/Tv-Channel-Logo/heads/main/CricHD/runded/12-by-xfireflix.png",
    group: "Sports",
  },
  skyscric: {
    url: "https://vlive.pages.dev/crichd?id=skyscric",
    name: "Sky Sports Cricket",
    logo: "https://raw.githubusercontent.com/abusaeeidx/Tv-Channel-Logo/heads/main/CricHD/runded/9-by-xfireflix.png",
    group: "Sports",
  },
  skysme: {
    url: "https://vlive.pages.dev/crichd?id=skysme",
    name: "Sky Cinema",
    logo: "https://raw.githubusercontent.com/abusaeeidx/Tv-Channel-Logo/heads/main/CricHD/runded/skycinema.png",
    group: "Sports",
  },
  bbtsp1: {
    url: "https://vlive.pages.dev/crichd?id=bbtsp1",
    name: "TNT 1",
    logo: "https://raw.githubusercontent.com/abusaeeidx/Tv-Channel-Logo/heads/main/CricHD/runded/tnt.png",
    group: "Sports",
  },
  bbtsp2: {
    url: "https://vlive.pages.dev/crichd?id=bbtsp2",
    name: "TNT 2",
    logo: "https://raw.githubusercontent.com/abusaeeidx/Tv-Channel-Logo/heads/main/CricHD/runded/tnt.png",
    group: "Sports",
  },
  bbtsp3: {
    url: "https://vlive.pages.dev/crichd?id=bbtsp3",
    name: "TNT 3",
    logo: "https://raw.githubusercontent.com/abusaeeidx/Tv-Channel-Logo/heads/main/CricHD/runded/tnt.png",
    group: "Sports",
  },
  bbtespn: {
    url: "https://vlive.pages.dev/crichd?id=bbtespn",
    name: "TNT 4",
    logo: "https://raw.githubusercontent.com/abusaeeidx/Tv-Channel-Logo/heads/main/CricHD/runded/tnt.png",
    group: "Sports",
  },
  skysact: {
    url: "https://vlive.pages.dev/crichd?id=skysact",
    name: "Sky Sports Action",
    logo: "https://raw.githubusercontent.com/abusaeeidx/Tv-Channel-Logo/heads/main/CricHD/runded/1745007829332.png",
    group: "Sports",
  },
  skysgol: {
    url: "https://vlive.pages.dev/crichd?id=skysgol",
    name: "Sky Sports Golf",
    logo: "https://raw.githubusercontent.com/abusaeeidx/Tv-Channel-Logo/heads/main/CricHD/runded/1745008055327.png",
    group: "Sports",
  },
  skysprem: {
    url: "https://vlive.pages.dev/crichd?id=skysprem",
    name: "Sky Sports Premier League",
    logo: "https://raw.githubusercontent.com/abusaeeidx/Tv-Channel-Logo/heads/main/CricHD/runded/43-by-xfireflix.png",
    group: "Sports",
  },
  skysfott: {
    url: "https://vlive.pages.dev/crichd?id=skysfott",
    name: "Sky Sports Football",
    logo: "https://raw.githubusercontent.com/abusaeeidx/Tv-Channel-Logo/heads/main/CricHD/runded/44-by-xfireflix.png",
    group: "Sports",
  },
  skysare: {
    url: "https://vlive.pages.dev/crichd?id=skysare",
    name: "Sky Sports Arena",
    logo: "https://raw.githubusercontent.com/abusaeeidx/Tv-Channel-Logo/heads/main/CricHD/runded/1745007829327.png",
    group: "Sports",
  },
  skysfor1: {
    url: "https://vlive.pages.dev/crichd?id=skysfor1",
    name: "Sky Sports F1",
    logo: "https://raw.githubusercontent.com/abusaeeidx/Tv-Channel-Logo/heads/main/CricHD/runded/1745008468637.png",
    group: "Sports",
  },
  laligauk: {
    url: "https://vlive.pages.dev/crichd?id=laligauk",
    name: "LaLiGA",
    logo: "https://raw.githubusercontent.com/abusaeeidx/Tv-Channel-Logo/heads/main/CricHD/runded/19-by-xfireflix.png",
    group: "Sports",
  },
  premieruk: {
    url: "https://vlive.pages.dev/crichd?id=premieruk",
    name: "Premier Sports 1",
    logo: "https://raw.githubusercontent.com/abusaeeidx/Tv-Channel-Logo/heads/main/CricHD/runded/31-by-xfireflix.png",
    group: "Sports",
  },
  hdchnl2: {
    url: "https://vlive.pages.dev/crichd?id=hdchnl2",
    name: "Premier Sports 2",
    logo: "https://raw.githubusercontent.com/abusaeeidx/Tv-Channel-Logo/heads/main/CricHD/runded/31-by-xfireflix.png",
    group: "Sports",
  },
  superfotball: {
    url: "https://vlive.pages.dev/crichd?id=superfotball",
    name: "Super Football",
    logo: "https://raw.githubusercontent.com/abusaeeidx/Tv-Channel-Logo/heads/main/CricHD/runded/34-by-xfireflix.png",
    group: "Sports",
  },
  superpremier: {
    url: "https://vlive.pages.dev/crichd?id=superpremier",
    name: "Super Premier League",
    logo: "https://raw.githubusercontent.com/abusaeeidx/Tv-Channel-Logo/heads/main/CricHD/runded/1745008781606.png",
    group: "Sports",
  },
  fox501: {
    url: "https://vlive.pages.dev/crichd?id=fox501",
    name: "Fox Cricket 501 HD",
    logo: "https://raw.githubusercontent.com/abusaeeidx/Tv-Channel-Logo/heads/main/CricHD/runded/6-by-xfireflix.png",
    group: "Sports",
  },
  espnusa: {
    url: "https://vlive.pages.dev/crichd?id=espnusa",
    name: "ESPN 1",
    logo: "https://raw.githubusercontent.com/abusaeeidx/Tv-Channel-Logo/heads/main/CricHD/runded/17-by-xfireflix.png",
    group: "Sports",
  },
  espn2: {
    url: "https://vlive.pages.dev/crichd?id=espn2",
    name: "ESPN 2",
    logo: "https://raw.githubusercontent.com/abusaeeidx/Tv-Channel-Logo/heads/main/CricHD/runded/17-by-xfireflix.png",
    group: "Sports",
  },
  skysmixx: {
    url: "https://vlive.pages.dev/crichd?id=skysmixx",
    name: "Sky Sports Mix",
    logo: "https://raw.githubusercontent.com/abusaeeidx/Tv-Channel-Logo/heads/main/CricHD/runded/13-by-xfireflix.png",
    group: "Sports",
  },
  skystennis: {
    url: "https://vlive.pages.dev/crichd?id=skystennis",
    name: "Sky Sports Tennis",
    logo: "https://raw.githubusercontent.com/abusaeeidx/Tv-Channel-Logo/heads/main/CricHD/runded/1745009085794.png",
    group: "Sports",
  },
  ten1hd: {
    url: "https://vlive.pages.dev/crichd?id=ten1hd",
    name: "Sony Sports3",
    logo: "https://raw.githubusercontent.com/abusaeeidx/Tv-Channel-Logo/heads/main/CricHD/runded/1000173192-modified.png",
    group: "Sports",
  },
  rokox: {
    url: "https://vlive.pages.dev/rokox",
    name: "Star Sports 1 Hindi",
    logo: "https://ltsk-cdn.s3.eu-west-1.amazonaws.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-60-j5fdr6a0-v1/imageContent-60-j5fdr6a0-m1.png",
    group: "Worldwide ðŸŒ",
  },
  "icc-shoq": {
    url: "https://vlive.pages.dev/prime?id=icc-shoq",
    name: "ICC LIVE SHOQ",
    logo: "https://iili.io/K4VqSPj.md.png",
    group: "sports",
  },

  fancode: {
    url: "https://vlive.pages.dev/fancode",
    name: "Fancode Web",
    logo: "https://iili.io/d5yvMLQ.md.png",
    group: "Website",
  },

  willowHD: {
    url: "https://vlive.pages.dev/prime?id=willow",
    name: "Willow HD",
    logo: "https://i.ibb.co/25LyH5D/20240727-041020.png",
    group: "Sports",
  },
  tnt1: {
    url: "https://vlive.pages.dev/prime?id=tnt1",
    name: "TNT SPORTS 1",
    logo: "https://iili.io/dIH66J4.png",
    group: "Sports",
  },
  tnt2: {
    url: "https://vlive.pages.dev/prime?id=tnt2",
    name: "TNT SPORTS 2",
    logo: "https://iili.io/dIH6rgf.png",
    group: "Sports",
  },
  tnt3: {
    url: "https://vlive.pages.dev/prime?id=tnt3",
    name: "TNT SPORTS 3",
    logo: "https://iili.io/dIH68sn.png",
    group: "Sports",
  },
  tnt4: {
    url: "https://vlive.pages.dev/prime?id=tnt4",
    name: "TNT SPORTS 4",
    logo: "https://iili.io/dIH6g0G.png",
    group: "Sports",
  },
  eurosport1: {
    url: "https://vlive.pages.dev/prime?id=eurosport1",
    name: "EURO SPORTS 1",
    logo: "https://iili.io/HpZ3vrx.png",
    group: "Sports",
  },
  eurosport2: {
    url: "https://vlive.pages.dev/prime?id=eurosport2",
    name: "EURO SPORTS 2",
    logo: "https://iili.io/HpZ3SdQ.png",
    group: "Sports",
  },
  beinsports1: {
    url: "https://vlive.pages.dev/prime?id=beinsports1",
    name: "BEIN SPORTS 1",
    logo: "https://iili.io/HpLlECJ.png",
    group: "Sports",
  },
  beinsports2: {
    url: "https://vlive.pages.dev/prime?id=beinsports2",
    name: "BEIN SPORTS 2",
    logo: "https://iili.io/HpLl0Qa.png",
    group: "Sports",
  },
  beinsports3: {
    url: "https://vlive.pages.dev/prime?id=beinsports3",
    name: "BEIN SPORTS 3",
    logo: "https://iili.io/HpLlGEv.png",
    group: "Sports",
  },
  fubosports2: {
    url: "https://vlive.pages.dev/prime?id=fubosports2",
    name: "Fubo Sports",
    logo: "https://iili.io/K4VYFvn.md.png",
    group: "Sports",
  },
  stansports: {
    url: "https://vlive.pages.dev/prime?id=stansports",
    name: "Stan Sports",
    logo: "https://iili.io/K4VMFI9.md.png",
    group: "Sports",
  },
  nba: {
    url: "https://vlive.pages.dev/prime?id=nba",
    name: "NBA LIVE",
    logo: "https://iili.io/K4VuON4.md.png",
    group: "Sports",
  },
  clq: {
    url: "https://vlive.pages.dev/prime?id=cl1",
    name: "CRICLIFE",
    logo: "https://i.ibb.co/jDyn9fS/Picsart-24-07-27-01-42-37-317.png",
    group: "Sports",
  },
  spotv: {
    url: "https://vlive.pages.dev/prime?id=spotv",
    name: "SPOTV",
    logo: "https://i.ibb.co/KGK6MNF/Picsart-24-07-27-01-35-56-981.png",
    group: "Sports",
  },
  spotv: {
    url: "https://vlive.pages.dev/prime?id=spotv2",
    name: "SPOTV 2",
    logo: "https://i.ibb.co/KGK6MNF/Picsart-24-07-27-01-35-56-981.png",
    group: "Sports",
  },

  tnt5: {
    url: "https://vlive.pages.dev/prime?id=tnt5",
    name: "TNT SPORTS 5",
    logo: "https://iili.io/dIH6Ufs.png",
    group: "Sports",
  },
  sports18: {
    url: "https://vlive.pages.dev/prime?id=sports18",
    name: "Sports 18-1",
    logo: "https://mediaready.videoready.tv/tatasky-epg/image/fetch/f_auto,fl_lossy,q_auto,dpr_6.75,w_40/https://ltsk-cdn.s3.eu-west-1.amazonaws.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-70046-l21cybww-v2/imageContent-70046-l21cybww-m5.png",
    group: "Sports",
  },
  sports18hd: {
    url: "https://vlive.pages.dev/prime?id=sports18hd",
    name: "Sports 18-1 HD",
    logo: "https://mediaready.videoready.tv/tatasky-epg/image/fetch/f_auto,fl_lossy,q_auto,dpr_6.75,w_40/https://ltsk-cdn.s3.eu-west-1.amazonaws.com/jumpstart/Temp_Live/cdn/HLS/Channel/imageContent-74232-la6z41u8-v3/imageContent-74232-la6z41u8-m5.png",
    group: "Sports",
  },
  skysports: {
    url: "https://live.dtvhindi.news/streaming?id=skysports&player=jwplayer",
    name: "Sky Sports Cricket",
    logo: "https://i.ibb.co/PCXT9Sz/Picsart-24-07-27-01-28-16-930.png",
    group: "Sports",
  },
  skysportscricket: {
    url: "https://ss.enamy3.workers.dev/?id=456239773",
    name: "Sky Sports Cricket",
    logo: "https://iili.io/dRwm9ou.md.png",
    group: "Sports",
  },
  pl1: {
    url: "https://vlive.pages.dev/prime?id=pl1",
    name: "Premier League",
    logo: "https://iili.io/21zCNB1.md.png",
    group: "Football",
  },
  pl2: {
    url: "https://vlive.pages.dev/prime?id=pl2",
    name: "Premier League 2",
    logo: "https://iili.io/21znF3u.md.png",
    group: "Football",
  },
  skysportsmainevent: {
    url: "https://vlive.pages.dev/prime?id=skysportsmainevent",
    name: "Sky Sports Mainevent",
    logo: "https://iili.io/dRwbpte.md.png",
    group: "Sports",
  },
  skysportsmix: {
    url: "https://vlive.pages.dev/prime?id=skysportsmix",
    name: "Sky Sports Mix",
    logo: "https://iili.io/dRwbbA7.md.png",
    group: "Sports",
  },
  skysportsaction: {
    url: "https://vlive.pages.dev/prime?id=skysportsaction",
    name: "Sky Sports Action",
    logo: "https://iili.io/dRwmHMb.md.png",
    group: "Sports",
  },
  skysportsfootball: {
    url: "https://vlive.pages.dev/prime?id=skysportsfootball",
    name: "Sky Sports Football",
    logo: "https://iili.io/dRwm2Kx.md.png",
    group: "Sports",
  },
  skysportspremierleague: {
    url: "https://vlive.pages.dev/prime?id=skysportspremierleague",
    name: "Sky Sports Premier League",
    logo: "https://iili.io/dRwm3cQ.md.png",
    group: "Sports",
  },
  skysportsarena: {
    url: "https://vlive.pages.dev/prime?id=skysportsarena",
    name: "Sky Sports Arena",
    logo: "https://iili.io/dRwmqAP.md.png",
    group: "Sports",
  },
  skysportsgolf: {
    url: "https://vlive.pages.dev/prime?id=skysportsgolf",
    name: "Sky Sports Golf",
    logo: "https://iili.io/dRwmTKv.md.png",
    group: "Sports",
  },
  skysportsf1: {
    url: "https://vlive.pages.dev/prime?id=skysportsf1",
    name: "Sky Sports F1",
    logo: "https://iili.io/dRwmziJ.md.png",
    group: "Sports",
  },

  "044": {
    url: "https://vlive.pages.dev/prime?id=ssc1",
    name: "SSC Sports 1",
    logo: "https://iili.io/HpLHT9n.png",
    group: "Sports",
  },
  "045": {
    url: "https://vlive.pages.dev/prime?id=ssc2",
    name: "SSC Sports 2",
    logo: "https://iili.io/HpLHxat.png",
    group: "Sports",
  },
  "046": {
    url: "https://vlive.pages.dev/prime?id=ssc3",
    name: "SSC Sports 3",
    logo: "https://iili.io/HpLHoFI.png",
    group: "Sports",
  },
  "047": {
    url: "https://vlive.pages.dev/prime?id=ssc4",
    name: "SSC Sports 4",
    logo: "https://iili.io/HpLHFwJ.png",
    group: "Sports",
  },
  "048": {
    url: "https://vlive.pages.dev/prime?id=ssc5",
    name: "SSC Sports 5",
    logo: "https://iili.io/HpLAKDx.png",
    group: "Sports",
  },
  epl1: {
    url: "https://vlive.pages.dev/prime?id=epl1",
    name: "Premier League",
    logo: "https://iili.io/dXNW8T7.md.png",
    group: "Football",
  },
  olympic1: {
    url: "https://vlive.pages.dev/prime?id=olympic1",
    name: "Olympics Channel 1",
    logo: "https://iili.io/du7WQKg.png",
    group: "Olympics",
  },
  olympic2: {
    url: "https://vlive.pages.dev/prime?id=olympic2",
    name: "Olympics Channel 1",
    logo: "https://iili.io/du7WQKg.png",
    group: "Olympics",
  },
  olympic3: {
    url: "https://vlive.pages.dev/prime?id=olympic3",
    name: "Olympics Channel 2",
    logo: "https://iili.io/du7WQKg.png",
    group: "Olympics",
  },
  olympic4: {
    url: "https://vlive.pages.dev/prime?id=olympic4",
    name: "Olympics Channel 2",
    logo: "https://iili.io/du7WQKg.png",
    group: "Olympics",
  },
  olympic5: {
    url: "https://vlive.pages.dev/prime?id=olympic5",
    name: "Olympics Channel 3",
    logo: "https://iili.io/du7WQKg.png",
    group: "Olympics",
  },
  olympic6: {
    url: "https://vlive.pages.dev/prime?id=olympic6",
    name: "Olympics Channel 3",
    logo: "https://iili.io/du7WQKg.png",
    group: "Olympics",
  },
  olympic7: {
    url: "https://vlive.pages.dev/prime?id=olympic7",
    name: "Olympics Channel 4",
    logo: "https://iili.io/du7WQKg.png",
    group: "Olympics",
  },
  olympic8: {
    url: "https://vlive.pages.dev/prime?id=olympic8",
    name: "Olympics Channel 4",
    logo: "https://iili.io/du7WQKg.png",
    group: "Olympics",
  },
  olympic9: {
    url: "https://vlive.pages.dev/prime?id=olympic9",
    name: "Olympics Channel 5",
    logo: "https://iili.io/du7WQKg.png",
    group: "Olympics",
  },
  olympic10: {
    url: "https://vlive.pages.dev/prime?id=olympic10",
    name: "Olympics Channel 5",
    logo: "https://iili.io/du7WQKg.png",
    group: "Olympics",
  },
  olympic11: {
    url: "https://vlive.pages.dev/prime?id=olympic11",
    name: "Olympics Channel 6",
    logo: "https://iili.io/du7WQKg.png",
    group: "Olympics",
  },
  olympic12: {
    url: "https://vlive.pages.dev/prime?id=olympic12",
    name: "Olympics Channel 6",
    logo: "https://iili.io/du7WQKg.png",
    group: "Olympics",
  },
  olympic13: {
    url: "https://vlive.pages.dev/prime?id=olympic13",
    name: "Olympics Channel 7",
    logo: "https://iili.io/du7WQKg.png",
    group: "Olympics",
  },
  olympic14: {
    url: "https://vlive.pages.dev/prime?id=olympic14",
    name: "Olympics Channel 7",
    logo: "https://iili.io/du7WQKg.png",
    group: "Olympics",
  },
  olympic15: {
    url: "https://vlive.pages.dev/prime?id=olympic15",
    name: "Olympics Channel 8",
    logo: "https://iili.io/du7WQKg.png",
    group: "Olympics",
  },
  olympic16: {
    url: "https://vlive.pages.dev/prime?id=olympic16",
    name: "Olympics Channel 8",
    logo: "https://iili.io/du7WQKg.png",
    group: "Olympics",
  },
  olympic17: {
    url: "https://vlive.pages.dev/prime?id=olympic17",
    name: "Olympics Channel 9",
    logo: "https://iili.io/du7WQKg.png",
    group: "Olympics",
  },
  olympic18: {
    url: "https://vlive.pages.dev/prime?id=olympic18",
    name: "Olympics Channel 9",
    logo: "https://iili.io/du7WQKg.png",
    group: "Olympics",
  },
  olympic19: {
    url: "https://vlive.pages.dev/prime?id=olympic19",
    name: "Olympics Channel 10",
    logo: "https://iili.io/du7WQKg.png",
    group: "Olympics",
  },
  olympic20: {
    url: "https://vlive.pages.dev/prime?id=olympic20",
    name: "Olympics Channel 10",
    logo: "https://iili.io/du7WQKg.png",
    group: "Olympics",
  },
  olympic21: {
    url: "https://vlive.pages.dev/prime?id=olympic21",
    name: "Olympics Channel 11",
    logo: "https://iili.io/du7WQKg.png",
    group: "Olympics",
  },
  olympic22: {
    url: "https://vlive.pages.dev/prime?id=olympic22",
    name: "Olympics Channel 11",
    logo: "https://iili.io/du7WQKg.png",
    group: "Olympics",
  },
  olympic23: {
    url: "https://vlive.pages.dev/prime?id=olympic23",
    name: "Olympics Channel 12",
    logo: "https://iili.io/du7WQKg.png",
    group: "Olympics",
  },
  olympic24: {
    url: "https://vlive.pages.dev/prime?id=olympic24",
    name: "Olympics Channel 12",
    logo: "https://iili.io/du7WQKg.png",
    group: "Olympics",
  },
  olympic25: {
    url: "https://vlive.pages.dev/prime?id=olympic25",
    name: "Olympics Channel 13",
    logo: "https://iili.io/du7WQKg.png",
    group: "Olympics",
  },
  olympic26: {
    url: "https://vlive.pages.dev/prime?id=olympic26",
    name: "Olympics Channel 13",
    logo: "https://iili.io/du7WQKg.png",
    group: "Olympics",
  },
  olympic27: {
    url: "https://vlive.pages.dev/prime?id=olympic27",
    name: "Olympics Channel 14",
    logo: "https://iili.io/du7WQKg.png",
    group: "Olympics",
  },
  olympic28: {
    url: "https://vlive.pages.dev/prime?id=olympic28",
    name: "Olympics Channel 14",
    logo: "https://iili.io/du7WQKg.png",
    group: "Olympics",
  },
  olympic29: {
    url: "https://vlive.pages.dev/prime?id=olympic29",
    name: "Olympics Channel 15",
    logo: "https://iili.io/du7WQKg.png",
    group: "Olympics",
  },
  olympic30: {
    url: "https://vlive.pages.dev/prime?id=olympic30",
    name: "Olympics Channel 15",
    logo: "https://iili.io/du7WQKg.png",
    group: "Olympics",
  },
  olympic31: {
    url: "https://vlive.pages.dev/prime?id=olympic31",
    name: "Olympics Channel 16",
    logo: "https://iili.io/du7WQKg.png",
    group: "Olympics",
  },

  skysports2: {
    url: "skysports",
    name: "Sky Sports Pl",
    logo: "https://iili.io/HpsO1kb.png",
    group: "Sports",
  },
};
